on:
    push:
      branches:
        - 'frontend'
  
permissions:
    contents: write
    packages: write
jobs:
    releases-matrix:
      strategy:
        matrix:
          arch: ['x64']
        max-parallel: 1
      name: Release Binary
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
            ref: 'frontend'
        - uses: pnpm/action-setup@v3
          with:
            version: 8
            run_install: |
              - recursive: true
        - name: build go template.
          run: |
            pnpm i
            pnpm run build
            mv build/index.html build/index.html.hbs
            mv build template
            tar -czvf front.tar.gz template
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            files: front.tar.gz 
            tag_name: latest
            name: frontend.tar.gz
            token: ${{ secrets.GITHUB_TOKEN }}
        