name: Release Rust bin
on:
    push:
        branches:
            - "backend"
jobs:
    release:
        name: release ${{ matrix.target }}
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            target: [x86_64-unknown-linux-musl]
        steps:
          - uses: actions/checkout@master
          - name: Compile and release
            id: compile
            uses: rust-build/rust-build.action@v1.4.5
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              RUSTTARGET: ${{ matrix.target }}
              TOOLCHAIN_VERSION: nightly
              EXTRA_FILES: "README.md LICENSE"
              UPLOAD_MODE: release
              MINIFY: true
          - name: Release
            uses: softprops/action-gh-release@v1
            with:
              files: |
                ${{ steps.compile.outputs.BUILT_ARCHIVE }}
                ${{ steps.compile.outputs.BUILT_CHECKSUM }}
              tag_name: latest
              name: emailvalidator_server.tar
              token: ${{ secrets.GITHUB_TOKEN }}
          